SET(ANDROID TRUE)
SET(ANDROID_NDK_PATH $ENV{ANDROID_NDK})
SET(ANDROID_TOOLCHAIN_PATH $ENV{ANDROID_TOOL_CHAIN})

#MESSAGE("Target:Android")
#MESSAGE("NDK PATH:" ${ANDROID_NDK_PATH})
#MESSAGE("ANDROID_TOOLCHAIN_PATH:" ${ANDROID_TOOLCHAIN_PATH})

# cross compile
SET(CMAKE_SYSTEM_NAME Linux) 
SET(CMAKE_FIND_ROOT_PATH ${ANDROID_TOOLCHAIN_PATH})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_C_COMPILER ${ANDROID_TOOLCHAIN_PATH}/bin/arm-linux-androideabi-gcc)
SET(CMAKE_CXX_COMPILER ${ANDROID_TOOLCHAIN_PATH}/bin/arm-linux-androideabi-g++)

# ndk
SET(ANDROID_SUPPORTED_ABIS_ARM "armeabi-v7a")
SET(ANDROID_DEFAULT_NDK_API_LEVEL 19)
